server:
   port: 8083

spring:
  application:
    name: API_GATEWAY
  
  cloud:
    gateway:
      routes:
      - id: CITIZEN-SERVICE
        uri:
          lb://CITIZEN-SERVICE
        predicates:
        - Path=/citizen/**
      - id: VACCINATION-CENTERE-SERVICE
        uri:
          lb://VACCINATION-CENTERE-SERVICE
        predicates:
        - Path=/vaccinationcenter/**
